.TH "__py__symbol_keyword_s" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__py__symbol_keyword_s \- Struct to define key words and symbol\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <python\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBsymbol\fP"
.br
.ti -1c
.RI "char * \fBkeyword\fP"
.br
.ti -1c
.RI "bool \fBname\fP"
.br
.ti -1c
.RI "int \fBargv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct to define key words and symbol\&. 
.PP
Definition at line 19 of file python\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int argv"

.PP
Definition at line 23 of file python\&.h\&.
.SS "char* keyword"

.PP
Definition at line 21 of file python\&.h\&.
.SS "bool name"

.PP
Definition at line 22 of file python\&.h\&.
.SS "char symbol"

.PP
Definition at line 20 of file python\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
