.TH "lib/formatstring Directory Reference" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/formatstring Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdisplaybinary\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaychar\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaynbr\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaynbr_dec\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaynbr_hexa\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaynbr_hexa_capital\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaynbr_octal\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaypercent\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaypointer\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaystr\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplaystr_unprintable\&.c\fP"
.br
.ti -1c
.RI "file \fBformatstring\&.c\fP"
.br
.ti -1c
.RI "file \fBformatstring\&.h\fP"
.br
.in -1c
