.TH "lib Directory Reference" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBformatstring\fP"
.br
.ti -1c
.RI "directory \fBmy\fP"
.br
.ti -1c
.RI "directory \fBmyprintf\fP"
.br
.in -1c
