.TH "lib/my Directory Reference" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconcat\&.c\fP"
.br
.ti -1c
.RI "file \fBinttochar\&.c\fP"
.br
.ti -1c
.RI "file \fBmy\&.h\fP"
.br
.ti -1c
.RI "file \fBmy_compute_power_rec\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_compute_square_root\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_find_prime_sup\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_getnbr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_intlen\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_is_prime\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_isneg\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putstarstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_revstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_show_word_array\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_showmem\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_showstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_sort_int_array\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_isalpha\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_islower\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_isnum\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_isprintable\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_isupper\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_to_word_array\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcapitalize\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcat\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strdup\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strlen\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strlowcase\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncat\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncmp\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strupcase\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_swap\&.c\fP"
.br
.in -1c
