.TH "src/buff_from_file.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/buff_from_file.c
.SH SYNOPSIS
.br
.PP
\fC#include 'esoterix\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBbuff_from_file\fP (char *file)"
.br
.RI "Get content of a file\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* buff_from_file (char * file)"

.PP
Get content of a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP name of the file to read
.RE
.PP
\fBReturns\fP
.RS 4
Content of the file 
.RE
.PP

.PP
Definition at line 18 of file buff_from_file\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
