.TH "lib/myprintf/displaynbr_octal.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/myprintf/displaynbr_octal.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include 'printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_getinoctal\fP (int nb)"
.br
.ti -1c
.RI "int \fBdisplaynbr_octal\fP (va_list argv)"
.br
.RI "Write an int in octal base in the standard output\&. "
.ti -1c
.RI "int \fBdisplaynbr_octal_hashtag\fP (va_list argv)"
.br
.RI "Write an int in octal base in the standard output\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int displaynbr_octal (va_list argv)"

.PP
Write an int in octal base in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargv\fP int to display
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 57 of file displaynbr_octal\&.c\&.
.SS "int displaynbr_octal_hashtag (va_list argv)"

.PP
Write an int in octal base in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargv\fP int to display
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 64 of file displaynbr_octal\&.c\&.
.SS "int my_getinoctal (int nb)"

.PP
Definition at line 34 of file displaynbr_octal\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
