.TH "lib/myprintf/displaypointer.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/myprintf/displaypointer.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_putadress\fP (long long nb)"
.br
.ti -1c
.RI "int \fBdisplaypointer\fP (va_list argv)"
.br
.RI "Write a pointer in the standard output\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int displaypointer (va_list argv)"

.PP
Write a pointer in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargv\fP string to display
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 40 of file displaypointer\&.c\&.
.SS "int my_putadress (long long nb)"

.PP
Definition at line 18 of file displaypointer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
