.TH "lib/myprintf/displaynbr_hexa.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/myprintf/displaynbr_hexa.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_putinhexa\fP (int nb)"
.br
.ti -1c
.RI "int \fBdisplaynbr_hexa\fP (va_list argv)"
.br
.RI "Write an int in hexadecimal format in the standard output\&. "
.ti -1c
.RI "int \fBdisplaynbr_hexa_hashtag\fP (va_list argv)"
.br
.RI "Write an int in hexadecimal format in the standard output\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int displaynbr_hexa (va_list argv)"

.PP
Write an int in hexadecimal format in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargv\fP int to display
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 40 of file displaynbr_hexa\&.c\&.
.SS "int displaynbr_hexa_hashtag (va_list argv)"

.PP
Write an int in hexadecimal format in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargv\fP int to display
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 47 of file displaynbr_hexa\&.c\&.
.SS "int my_putinhexa (int nb)"

.PP
Definition at line 18 of file displaynbr_hexa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
