.TH "lib/myprintf/displaystr_unprintable.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/myprintf/displaystr_unprintable.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdisplayoctal\fP (int nb)"
.br
.ti -1c
.RI "int \fBdisplaystr_unprintable\fP (va_list argv)"
.br
.RI "Write a string with unprintable characters in the standard output\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int displayoctal (int nb)"

.PP
Definition at line 28 of file displaystr_unprintable\&.c\&.
.SS "int displaystr_unprintable (va_list argv)"

.PP
Write a string with unprintable characters in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargv\fP string to display
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 52 of file displaystr_unprintable\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
