.TH "lib/myprintf/displaypercent.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/myprintf/displaypercent.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include 'printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdisplaypercent\fP (__attribute__((unused)) va_list argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int displaypercent (__attribute__((unused)) va_list argv)"

.PP
Definition at line 16 of file displaypercent\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
