.TH "filetype_s" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filetype_s \- Struct for a type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esoterix\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfileref_t\fP \fBreference\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char *(* \fBfunc\fP )(char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for a type\&. 

Contain the reference to the type to compile, his abbreviations, and a pointer to the function 
.PP
Definition at line 161 of file esoterix\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* filename"

.PP
Definition at line 163 of file esoterix\&.h\&.
.SS "char*( * func(char *)"

.PP
Definition at line 164 of file esoterix\&.h\&.
.SS "\fBfileref_t\fP reference"

.PP
Definition at line 162 of file esoterix\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
