.TH "flags" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flags \- Struct for a flag,\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <printf\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBfunc\fP )(va_list)"
.br
.ti -1c
.RI "char \fBflag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for a flag,\&. 

Contains a pointer on function for the flag and the flag 
.PP
Definition at line 183 of file printf\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char flag"

.PP
Definition at line 185 of file printf\&.h\&.
.SS "int(* func)(va_list)"

.PP
Definition at line 184 of file printf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
