.TH "src/main.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'esoterix\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (\fBUNUSED\fP int ac, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBfiletype_t\fP \fBFiles\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (\fBUNUSED\fP int ac, char ** argv)"

.PP
Definition at line 33 of file main\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBfiletype_t\fP Files[]"
\fBInitial value:\fP
.PP
.nf
= {
    {PYTHON, "py", __python__},
    {C, "c", NULL},
    {CPP, "cpp", NULL},
    {LUA, "lua", NULL},
    {JAVA, "java", NULL},
    {GO, "go", NULL},
    {JAVASCRIPT, "js", NULL},
    {WHITESPACE, "ws", NULL},
    {UNLAMBDA, "ul", NULL},
    {MALBOLGE, "mbg", NULL},
    {LOLCODE, "llcd", NULL},
    {JSFUCK, "jsf", NULL},
    {INTERCAL, "ic", NULL},
    {GOLFSCRIPT, "gscript", NULL},
    {FRACTAN, "frctn", NULL},
    {BLC, "blc", NULL},
    {BEFUNGE, "bfng", NULL},
    {SHEAKSPEAR, "shspr", NULL},
    {BRAINFUCK, "bf", NULL},
    {CHEF, "chef", NULL}
}
.fi
.PP
Definition at line 10 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
