.TH "lib/my/my_compute_square_root.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_compute_square_root.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_compute_square_root\fP (int nb)"
.br
.RI "Get the square root of an int\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_compute_square_root (int nb)"

.PP
Get the square root of an int\&. 
.PP
\fBParameters\fP
.RS 4
\fInb\fP number to check
.RE
.PP
\fBReturns\fP
.RS 4
Square root of the argument 
.RE
.PP

.PP
Definition at line 8 of file my_compute_square_root\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
