.TH "lib/my/my_compute_power_rec.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_compute_power_rec.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpower\fP (int res, int nb, int p)"
.br
.ti -1c
.RI "int \fBmy_compute_power_rec\fP (int nb, int p)"
.br
.RI "Get a number at a given power recursively\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_compute_power_rec (int nb, int power)"

.PP
Get a number at a given power recursively\&. 
.PP
\fBParameters\fP
.RS 4
\fInb\fP number 
.br
\fIpower\fP power
.RE
.PP
\fBReturns\fP
.RS 4
Number at power given 
.RE
.PP

.PP
Definition at line 17 of file my_compute_power_rec\&.c\&.
.SS "int power (int res, int nb, int p)"

.PP
Definition at line 8 of file my_compute_power_rec\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
