.TH "lib/my/my_find_prime_sup.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_find_prime_sup.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_is_prime\fP (int nb)"
.br
.RI "Check if a number is prime\&. "
.ti -1c
.RI "int \fBmy_find_prime_sup\fP (int nb)"
.br
.RI "Get the first superior prime number\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_find_prime_sup (int nb)"

.PP
Get the first superior prime number\&. 
.PP
\fBParameters\fP
.RS 4
\fInb\fP number to check
.RE
.PP
\fBReturns\fP
.RS 4
First prime number superior to the argument 
.RE
.PP

.PP
Definition at line 10 of file my_find_prime_sup\&.c\&.
.SS "int my_is_prime (int nb)"

.PP
Check if a number is prime\&. 
.PP
\fBParameters\fP
.RS 4
\fInb\fP number to check
.RE
.PP
\fBReturns\fP
.RS 4
1 if is prime, 0 otherwise 
.RE
.PP

.PP
Definition at line 8 of file my_is_prime\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
