.TH "lib/my/my_getnbr.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_getnbr.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_getnbr\fP (char const *str)"
.br
.RI "Get a number from a string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_getnbr (char const * str)"

.PP
Get a number from a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to check
.RE
.PP
\fBReturns\fP
.RS 4
Number from the string 
.RE
.PP

.PP
Definition at line 8 of file my_getnbr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
