.TH "lib/my/my_isneg.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_isneg.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_putchar\fP (char c)"
.br
.ti -1c
.RI "int \fBmy_isneg\fP (int n)"
.br
.RI "Check if a number is negative\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_isneg (int nb)"

.PP
Check if a number is negative\&. 
.PP
\fBParameters\fP
.RS 4
\fInb\fP number to check
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 10 of file my_isneg\&.c\&.
.SS "void my_putchar (char c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
