.TH "lib/my/my_intlen.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_intlen.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_intlen\fP (int x)"
.br
.RI "Get lenth of an int\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_intlen (int x)"

.PP
Get lenth of an int\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP number to check
.RE
.PP
\fBReturns\fP
.RS 4
Length of the int 
.RE
.PP

.PP
Definition at line 8 of file my_intlen\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
