.TH "lib/my/my_putstarstr.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_putstarstr.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_putchar\fP (char c)"
.br
.ti -1c
.RI "void \fBmy_putstr\fP (char *c)"
.br
.ti -1c
.RI "void \fBmy_putstarstr\fP (char **str, int nb_rows, char *separator)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void my_putchar (char c)"

.SS "void my_putstarstr (char ** str, int nb_rows, char * separator)"

.PP
Definition at line 14 of file my_putstarstr\&.c\&.
.SS "void my_putstr (char * c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
