.TH "lib/my/my_revstr.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_revstr.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_strlen\fP (char *str)"
.br
.ti -1c
.RI "char * \fBmy_revstr\fP (char *str)"
.br
.RI "Reverse a string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_revstr (char * str)"

.PP
Reverse a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to reverse
.RE
.PP
\fBReturns\fP
.RS 4
String reverse 
.RE
.PP

.PP
Definition at line 12 of file my_revstr\&.c\&.
.SS "int my_strlen (char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
