.TH "lib/my/my_strncat.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strncat.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strncat\fP (char *dest, char const *src, int nb)"
.br
.RI "Concat a string into an other string on n characters\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strncat (char * dest, char const * src, int nb)"

.PP
Concat a string into an other string on n characters\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP destination string 
.br
\fIsrc\fP source string 
.br
\fInb\fP nb of characters to check
.RE
.PP
\fBReturns\fP
.RS 4
Destination string with copied source string on n characters 
.RE
.PP

.PP
Definition at line 10 of file my_strncat\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
