.TH "lib/my/my_swap.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_swap.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_swap\fP (int *a, int *b)"
.br
.RI "Swap to int\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void my_swap (int * a, int * b)"

.PP
Swap to int\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP first int 
.br
\fIb\fP second int 
.RE
.PP

.PP
Definition at line 8 of file my_swap\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
