.TH "lib/my/my_sort_int_array.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_sort_int_array.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap\fP (int *array, int a, int b)"
.br
.ti -1c
.RI "int \fBcompare\fP (int *array, int i, int sorted)"
.br
.ti -1c
.RI "void \fBmy_sort_int_array\fP (int *array, int size)"
.br
.RI "Write an int array in the standard output\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int compare (int * array, int i, int sorted)"

.PP
Definition at line 19 of file my_sort_int_array\&.c\&.
.SS "void my_sort_int_array (int * tab, int size)"

.PP
Write an int array in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fItab\fP int array 
.br
\fIsize\fP size of the int array 
.RE
.PP

.PP
Definition at line 28 of file my_sort_int_array\&.c\&.
.SS "void swap (int * array, int a, int b)"

.PP
Definition at line 10 of file my_sort_int_array\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
