.TH "lib/my/my_showmem.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_showmem.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_showmem\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_showmem (void)"

.PP
Definition at line 8 of file my_showmem\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
