.TH "lib/my/my_str_islower.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_str_islower.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_str_islower\fP (char const *str)"
.br
.RI "Check if a string contain only lower characters\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_str_islower (char const * str)"

.PP
Check if a string contain only lower characters\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to check
.RE
.PP
\fBReturns\fP
.RS 4
0 if contains only lower characters, 1 otherwise 
.RE
.PP

.PP
Definition at line 10 of file my_str_islower\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
