.TH "lib/my/my_strncmp.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strncmp.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_strncmp\fP (char const *s1, char const *s2, int n)"
.br
.RI "Compare firsts characters of two string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_strncmp (char const * s1, char const * s2, int n)"

.PP
Compare firsts characters of two string\&. 
.PP
\fBParameters\fP
.RS 4
\fIs1\fP string to check 
.br
\fIs2\fP string to check 
.br
\fIn\fP number of characters to compare
.RE
.PP
\fBReturns\fP
.RS 4
0 if equal, difference between otherwise 
.RE
.PP

.PP
Definition at line 8 of file my_strncmp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
