.TH "lib/my/my_strncpy.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strncpy.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strncpy\fP (char *dest, char const *src, int n)"
.br
.RI "Copy firsts characters of a string into an other string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strncpy (char * dest, char const * src, int n)"

.PP
Copy firsts characters of a string into an other string\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP destination string 
.br
\fIsrc\fP source string 
.br
\fIn\fP number of characters to copy
.RE
.PP
\fBReturns\fP
.RS 4
Destination string with copied source string 
.RE
.PP

.PP
Definition at line 8 of file my_strncpy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
