.TH "lib/my/my_strcat.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strcat.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strcat\fP (char *dest, char const *src)"
.br
.RI "Concat a string into an other string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcat (char * dest, char const * src)"

.PP
Concat a string into an other string\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP destination string 
.br
\fIsrc\fP source string
.RE
.PP
\fBReturns\fP
.RS 4
Destination string with copied source string 
.RE
.PP

.PP
Definition at line 10 of file my_strcat\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
