.TH "lib/my/my_show_word_array.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_show_word_array.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_putstr\fP (char const *str)"
.br
.RI "Write a string in the standard output\&. "
.ti -1c
.RI "int \fBmy_show_word_array\fP (char *const *tab)"
.br
.RI "Write a string array in the standard output\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_putstr (char const * str)"

.PP
Write a string in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to write
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 11 of file my_putstr\&.c\&.
.SS "int my_show_word_array (char *const * tab)"

.PP
Write a string array in the standard output\&. 
.PP
\fBParameters\fP
.RS 4
\fItab\fP array to write
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.PP
Definition at line 12 of file my_show_word_array\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
