.TH "lib/my/my_strdup.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strdup.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_strlen\fP (char const *str)"
.br
.RI "Get the lenth of a string\&. "
.ti -1c
.RI "char * \fBmy_strcpy\fP (char *dest, char const *src)"
.br
.ti -1c
.RI "char * \fBmy_strdup\fP (char const *str)"
.br
.RI "Make a copy of a string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcpy (char * dest, char const * src)"

.PP
Definition at line 10 of file my_strcpy\&.c\&.
.SS "char* my_strdup (char const * str)"

.PP
Make a copy of a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP Copy the string
.RE
.PP
\fBReturns\fP
.RS 4
String copy 
.RE
.PP

.PP
Definition at line 14 of file my_strdup\&.c\&.
.SS "int my_strlen (char const * str)"

.PP
Get the lenth of a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to check
.RE
.PP
\fBReturns\fP
.RS 4
Length of the string 
.RE
.PP

.PP
Definition at line 10 of file my_strlen\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
