.TH "lib/my/my_strlowcase.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strlowcase.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strlowcase\fP (char *str)"
.br
.RI "Set a string to lower case\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strlowcase (char * str)"

.PP
Set a string to lower case\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP base string
.RE
.PP
\fBReturns\fP
.RS 4
String set to lower case 
.RE
.PP

.PP
Definition at line 8 of file my_strlowcase\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
