.TH "lib/my/my_strcpy.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strcpy.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strcpy\fP (char *dest, char const *src)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcpy (char * dest, char const * src)"

.PP
Definition at line 10 of file my_strcpy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
