.TH "test" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBa\fP = 3"
.br
.ti -1c
.RI "\fBb\fP = print('hello')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int a = 3"

.PP
Definition at line 1 of file test\&.py\&.
.SS "b = print('hello')"

.PP
Definition at line 2 of file test\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
