.TH "test/test.py" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBa\fP = 3"
.br
.ti -1c
.RI "\fBb\fP = print('hello')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
