.TH "src/encrypt/python/values.c" 3 "Thu Jun 23 2022" "Version 1.0" "Esoterix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/encrypt/python/values.c
.SH SYNOPSIS
.br
.PP
\fC#include 'esoterix\&.h'\fP
.br
\fC#include 'python\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fB__py__var_from_value\fP (int nb, char *values)"
.br
.ti -1c
.RI "char * \fB__py__values_from_var\fP (int nb, char *values)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* __py__values_from_var (int nb, char * values)"

.PP
Definition at line 21 of file values\&.c\&.
.SS "char* __py__var_from_value (int nb, char * values)"

.PP
Definition at line 11 of file values\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Esoterix from the source code\&.
