array.c
bool is_in(char **array, char *str)
Check if a string is in an array.
array array to check str string to check true if str is in array, false otherwise
References my_strcmp.
Referenced by no_double, remove_all.
char** append(char **array, char *str)
Add a string in an Array.
array array to check str string to check array with the string
References my_strarraylen.
Referenced by __py__get_func, no_double.
char** remove(char **array, char *str)
Remove first occurence of a string in an array.
array array to check str string to check array without the string
References my_strarraylen, my_strcmp.
Referenced by __python__, getvar, remove_all.
char** remove_all(char **array, char *str)
Delete all time str in array.
array array to clean str string to delete array without the string
References is_in, remove.
char** no_double(char **array)
Delete double in an array.
array array to check array without double
References append, is_in, my_strarraylen.
Referenced by __py__get_func, getvar.