esoterix.h
INIT_ARRAY
Initialize an empty array.
LAST_ARRAY
Get the last element of an array.
LAST_STR
Get the last element of a string.
FREE_ARRAY
Free an array.
SHOW_ARRAY
Show an array.
fileref_e
typedef struct filetype_s filetype_t
Includes.
Typedefs
typedef enum fileref_e fileref_t
char* buff_from_file(char *file)
Get content of a file.
file name of the file to read Content of the file
References build.file.
Referenced by __python__.
char* __python__(char *file)
Translate python script in language X.
file name of the file to read Content traduce
References __py__fcnt_display, __py__get_func, buff_from_file, build.file, format, getvar, my_str_to_word_array, my_strdup, pywords, remove.
char** remove_all(char **array, char *str)
Delete all time str in array.
array array to clean str string to delete array without the string
References is_in, remove.
bool is_in(char **array, char *str)
Check if a string is in an array.
array array to check str string to check true if str is in array, false otherwise
References my_strcmp.
Referenced by no_double, remove_all.
char** remove(char **array, char *str)
Remove first occurence of a string in an array.
array array to check str string to check array without the string
References my_strarraylen, my_strcmp.
Referenced by __python__, getvar, remove_all.
char** append(char **array, char *str)
Add a string in an Array.
array array to check str string to check array with the string
References my_strarraylen.
Referenced by __py__get_func, no_double.
char** no_double(char **array)
Delete double in an array.
array array to check array without double
References append, is_in, my_strarraylen.
Referenced by __py__get_func, getvar.