formatstring.c
const struct fflags Functions[][]
const struct fflags Hashtags[][]
static int my_strlen(char const *str)
char* fus(char *a, char *b)
Fusion of two strings.
a first string b second string String of the fusion
Referenced by fdisplaynbr_dec, fdisplaynbr_hexa_capital_hashtag, fdisplaynbr_hexa_hashtag, fdisplaynbr_octal, fdisplaypointer, fmy_put_nbr_dec, format.
char* fdisplayhashtag(char c, va_list argv)
char* fdisplayflags(char c, va_list argv)
Referenced by format.
char* format(char const *str,...)
Format string representation.
str string to format ... list of arguments String of the string
References fdisplayflags, fus.
Referenced by __py__fcnt_display, __python__, var_from_array.