get_functions.c
int chr_in_array(char c, char *array)
Referenced by __py__get_func.
char** __py__get_func(char **functions)
Get function name.
functions all name to check array of function name
References append, chr_in_array, INIT_ARRAY, LAST_ARRAY, my_strdup, my_strlen, no_double.
Referenced by __python__.
char* __py__fcnt_display(char **array)
Get function printing string.
array all name to check array of function printing string
References format.
Referenced by __python__.