my_strcmp.c
int my_strlen(char const *str)
Get the lenth of a string.
str string to check Length of the string
Referenced by my_strcmp.
int my_strncmp(char const *s1, char const *s2, int n)
Compare firsts characters of two string.
s1 string to check s2 string to check n number of characters to compare 0 if equal, difference between otherwise
References test.a, test.b.
Referenced by my_strcmp.
int my_strcmp(char const *s1, char const *s2)
Compare two string.
s1 string to check s2 string to check 0 if equal, difference between otherwise
References my_strlen, my_strncmp.
Referenced by is_in, main, remove.