my_strdup.c
int my_strlen(char const *str)
Get the lenth of a string.
str string to check Length of the string
Referenced by my_strdup.
char* my_strcpy(char *dest, char const *src)
Referenced by my_strdup.
char* my_strdup(char const *str)
Make a copy of a string.
str Copy the string String copy
References my_strcpy, my_strlen.
Referenced by __py__get_func, __py__values_from_var, __py__var_from_value, __python__, getvar.