my_str_to_word_array.c
int my_strlen(char const *str)
Get the lenth of a string.
str string to check Length of the string
static bool is_sep(char c, char *separators)
static int count_line(char *str, char *separator)
static int size_str(char *str, int i, char *separator)
static char* fill_array(char *str, int i, char *separator)
char** my_str_to_word_array(char *str, char *separator)
Turn a string into an array.
str string to transform sep separator to transform Array of string
Referenced by __py__values_from_var, __py__var_from_value, __python__, getvar, main.