my_strlen.c
int my_strlen(char const *str)
Get the lenth of a string.
str string to check Length of the string
Referenced by __py__get_func, concat, displaystr, my_putstr, my_strcmp, my_strdup, my_strstr.
int my_strarraylen(char const **str)