my_printf.c
const struct flags Functions[][]
const struct flags Hashtags[][]
static void my_putchar(char c)
int displayhashtag(char c, va_list argv)
Referenced by my_printf.
int displayflags(char c, va_list argv)
Referenced by my_printf.
int my_printf(char const *str,...)
Write a string with arguments in the standard output.
argv string to display ... params for the string 0
References displayflags, displayhashtag.
Referenced by getvar, main.